[package]
name = "zarrs_regression_testing"
version = "0.1.0"
authors = ["Lachlan Deakin <ljdgit@gmail.com>"]
edition = "2024"
rust-version = "1.92"
description = "Data compatibility tests between the workspace zarrs crate and previous zarrs releases"
homepage = "https://zarrs.dev"
repository = "https://github.com/zarrs/zarrs"
license = "MIT OR Apache-2.0"
publish = false

[lints]
workspace = true

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
proptest = "1.6"
rayon = "1.10.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = { version = "1.0.71", features = ["float_roundtrip", "preserve_order"] }
zarrs = { path = "../zarrs", default-features = false, features = [
    "filesystem",
    "adler32",
    "bitround",
    "blosc",
    "bz2",
    "crc32c",
    "fletcher32",
    "gdeflate",
    "gzip",
    "microfloat",
    "pcodec",
    "transpose",
    "zfp",
    "zlib",
    "zstd",
] }

[dev-dependencies]
inventory.workspace = true
zarrs_codec.workspace = true
zarrs_data_type.workspace = true
